name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Delete old images
        run: sudo docker system prune -a -f --volumes || true
      - name: Pull Docker image
        run: sudo docker pull eliotatlani31/file-converter:latest
      - name: Delete Old Docker
        run: sudo docker rm -f file-converter || true
      - name:
          Run Docker container
          # Add more environment variables as needed
        run: |
          sudo docker run -d -p 8000:8000 \
          -e NUM_CORES=2 \
          --name file-converter \
          eliotatlani31/file-converter
